language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: pip install -r requirements.txt --use-mirrors
# Start MongoDB
services: mongodb
# command to run tests
script:
  - "flake8"
  - "./run_tests.sh"
