#!/bin/sh
curl -v -X POST -d '{
  "name": "BasicReport",
  "fields": {
      "title": {"type": "StringField", "max_length": 255, "required": true},
      "desc": {"type": "StringField", "required": true}
      },
  "description": "Basic location based report",
  "keywords": ["location", "report"],
  "group": "location based reports",
  "service_name": "basic report",
  "service_code": "0001"
}' -H "Content-Type: application/json" localhost:5000/services
