#!/bin/sh
curl -v -X POST -d '{
  "classname": "BasicReportCreatedViaCurl",
  "fields": [{"name": "title", "fieldtype": "StringField", "max_length": 255, "required": true},
             {"name": "desc", "fieldtype": "StringField", "required": true}],
  "description": "Basic location based report created from curl script",
  "keywords": ["location", "report"],
  "group": "location based reports",
  "service_name": "basic report",
  "service_code": "curl0001"
}' -H "Content-Type: application/json" localhost:5000/services
